name: testing

on:
  push:
    branches: master
  pull_request:

permissions: read-all

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    name: unit test with Python ${{ matrix.python-version }} and Markdown ${{ matrix.markdown-version }}
    strategy:
      matrix:
        python-version: [3.5]
        markdown-version: [2.6.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Execute tests
        run: |
          pip install Markdown==${{ matrix.markdown-version }}
          python setup.py test
